
var FFmpegThumb = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var e=moduleArg,h,k,aa=new Promise((a,b)=>{h=a;k=b}),ba="object"==typeof window,p="undefined"!=typeof WorkerGlobalScope,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,ca=Object.assign({},e),u="./this.program",v=(a,b)=>{throw b;},w="",x,z;
if(0){var fs={};w="";z=a=>{a=da(a)?new URL(a):a;return fs.readFileSync(a)};x=async a=>{a=da(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!e.thisProgram&&1<process.argv.length&&(u=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);v=(a,b)=>{process.exitCode=a;throw b;}}else if(0)p?w=self.location.href:"undefined"!=typeof document&&document.currentScript&&(w=document.currentScript.src),_scriptName&&(w=_scriptName),w.startsWith("blob:")?w="":w=w.substr(0,
w.replace(/[?#].*/,"").lastIndexOf("/")+1),p&&(z=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),x=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ea=e.print||console.log.bind(console),A=e.printErr||console.error.bind(console);Object.assign(e,ca);ca=null;e.thisProgram&&(u=e.thisProgram);var B=e.wasmBinary,C,D=!1,E,F,G,fa,H,I;
function ha(){var a=C.buffer;e.HEAP8=F=new Int8Array(a);e.HEAP16=fa=new Int16Array(a);e.HEAPU8=G=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=H=new Int32Array(a);e.HEAPU32=I=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var ia=[],ja=[],ka=[];function la(){var a=e.preRun.shift();ia.unshift(a)}var J=0,L=null;
function ma(a){e.onAbort?.(a);a="Aborted("+a+")";A(a);D=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");k(a);throw a;}var na=a=>a.startsWith("data:application/octet-stream;base64,"),da=a=>a.startsWith("file://"),M;async function oa(a){if(!B)try{var b=await x(a);return new Uint8Array(b)}catch{}if(a==M&&B)a=new Uint8Array(B);else if(z)a=z(a);else throw"both async and sync fetching of the wasm failed";return a}
async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}async function qa(a){var b=M;if(!B&&"function"==typeof WebAssembly.instantiateStreaming&&!na(b)&&!r&&"function"==typeof fetch)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return pa(b,a)}var N,O;
class P{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Q=a=>{for(;0<a.length;)a.shift()(e)},R=e.noExitRuntime||!0,ra="undefined"!=typeof TextDecoder?new TextDecoder:void 0,sa=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&ra)return ra.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,
56320|f&1023))}}else c+=String.fromCharCode(f)}return c},S=0,ta=a=>0===a%4&&(0!==a%100||0===a%400),ua=[0,31,60,91,121,152,182,213,244,274,305,335],va=[0,31,59,90,120,151,181,212,243,273,304,334],T={},wa=a=>{E=a;R||0<S||(e.onExit?.(a),D=!0);v(a,new P(a))},xa=a=>{if(!D)try{if(a(),!(R||0<S))try{E=a=E,wa(a)}catch(b){b instanceof P||"unwind"==b||v(1,b)}}catch(b){b instanceof P||"unwind"==b||v(1,b)}},U=(a,b,c)=>{var d=G;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=
g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}},V={},ya=()=>{if(!W){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",
_:u||"./this.program"},b;for(b in V)void 0===V[b]?delete a[b]:a[b]=V[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);W=c}return W},W,za=[null,[],[]],Ca=(a,b,c,d)=>{var f={string:m=>{var n=0;if(null!==m&&void 0!==m&&0!==m){for(var t=n=0;t<m.length;++t){var K=m.charCodeAt(t);127>=K?n++:2047>=K?n+=2:55296<=K&&57343>=K?(n+=4,++t):n+=3}n+=1;t=X(n);U(m,t,n);n=t}return n},array:m=>{var n=X(m.length);F.set(m,n);return n}};a=e["_"+a];var g=[],l=0;if(d)for(var q=0;q<d.length;q++){var y=f[c[q]];y?(0===l&&(l=Aa()),
g[q]=y(d[q])):g[q]=d[q]}c=a(...g);return c=function(m){0!==l&&Ba(l);return"string"===b?m?sa(G,m):"":"boolean"===b?!!m:m}(c)},Fa={b:function(){return 0},v:function(){return 0},t:function(){},g:()=>ma(""),q:()=>{R=!1;S=0},j:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));H[c>>2]=a.getUTCSeconds();H[c+4>>2]=a.getUTCMinutes();H[c+8>>2]=a.getUTCHours();H[c+12>>2]=a.getUTCDate();H[c+16>>2]=a.getUTCMonth();H[c+20>>2]=a.getUTCFullYear()-1900;H[c+24>>2]=a.getUTCDay();H[c+
28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},k:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));H[c>>2]=a.getSeconds();H[c+4>>2]=a.getMinutes();H[c+8>>2]=a.getHours();H[c+12>>2]=a.getDate();H[c+16>>2]=a.getMonth();H[c+20>>2]=a.getFullYear()-1900;H[c+24>>2]=a.getDay();H[c+28>>2]=(ta(a.getFullYear())?ua:va)[a.getMonth()]+a.getDate()-1|0;H[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();H[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},m:function(a){var b=new Date(H[a+20>>2]+1900,H[a+16>>2],H[a+12>>2],H[a+8>>2],H[a+4>>2],H[a>>2],0),c=H[a+32>>2],d=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),l=Math.min(g,f);0>c?H[a+32>>2]=Number(f!=g&&l==d):0<c!=(l==d)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));H[a+24>>2]=b.getDay();H[a+28>>2]=(ta(b.getFullYear())?
ua:va)[b.getMonth()]+b.getDate()-1|0;H[a>>2]=b.getSeconds();H[a+4>>2]=b.getMinutes();H[a+8>>2]=b.getHours();H[a+12>>2]=b.getDate();H[a+16>>2]=b.getMonth();H[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;Da((N=a,1<=+Math.abs(N)?0<N?+Math.floor(N/4294967296)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0));return a>>>0},r:(a,b)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!b)return 0;var c=setTimeout(()=>{delete T[a];xa(()=>Ea(a,performance.now()))},b);T[a]={id:c,D:b};return 0},u:(a,b,
c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();I[a>>2]=60*Math.max(g,f);H[b>>2]=Number(g!=f);b=l=>{var q=Math.abs(l);return`UTC${0<=l?"-":"+"}${String(Math.floor(q/60)).padStart(2,"0")}${String(q%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(U(a,c,17),U(b,d,17)):(U(a,d,17),U(b,c,17))},o:function(a,b,c,d){if(!(0<=a&&3>=a))return 28;a=Math.round(1E6*(0===a?Date.now():performance.now()));O=[a>>>0,(N=a,1<=+Math.abs(N)?0<N?+Math.floor(N/
4294967296)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];H[d>>2]=O[0];H[d+4>>2]=O[1];return 0},f:()=>Date.now(),a:()=>performance.now(),s:a=>{var b=G.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-C.buffer.byteLength+65535)/65536|0;try{C.grow(d);ha();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},d:(a,b)=>{var c=0;ya().forEach((d,f)=>{var g=b+c;f=I[a+4*f>>2]=
g;for(g=0;g<d.length;++g)F[f++]=d.charCodeAt(g);F[f]=0;c+=d.length+1});return 0},e:(a,b)=>{var c=ya();I[a>>2]=c.length;var d=0;c.forEach(f=>d+=f.length+1);I[b>>2]=d;return 0},l:()=>52,c:(a,b)=>{var c=0;if(0==a)c=2;else if(1==a||2==a)c=64;F[b]=2;fa[b+2>>1]=1;O=[c>>>0,(N=c,1<=+Math.abs(N)?0<N?+Math.floor(N/4294967296)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];H[b+8>>2]=O[0];H[b+12>>2]=O[1];O=[0,(N=0,1<=+Math.abs(N)?0<N?+Math.floor(N/4294967296)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>
0:0)];H[b+16>>2]=O[0];H[b+20>>2]=O[1];return 0},i:()=>52,n:function(){return 70},h:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var l=I[b>>2],q=I[b+4>>2];b+=8;for(var y=0;y<q;y++){var m=a,n=G[l+y],t=za[m];0===n||10===n?((1===m?ea:A)(sa(t)),t.length=0):t.push(n)}f+=q}I[d>>2]=f;return 0},p:wa},Y;
(async function(){function a(d){Y=d.exports;C=Y.w;ha();ja.unshift(Y.x);J--;e.monitorRunDependencies?.(J);0==J&&L&&(d=L,L=null,d());return Y}J++;e.monitorRunDependencies?.(J);var b={a:Fa};if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(d){A(`Module.instantiateWasm callback failed with error: ${d}`),k(d)}M??=na("ffmpeg-thumb.wasm")?"ffmpeg-thumb.wasm":e.locateFile?e.locateFile("ffmpeg-thumb.wasm",w):w+"ffmpeg-thumb.wasm";try{var c=await qa(b);a(c.instance);return c}catch(d){k(d)}})();
e._decode_first_idr_to_jpeg=(a,b,c,d,f,g,l)=>(e._decode_first_idr_to_jpeg=Y.y)(a,b,c,d,f,g,l);e._free_jpeg=a=>(e._free_jpeg=Y.z)(a);e._free=a=>(e._free=Y.A)(a);e._remux_ts_to_mp4=(a,b,c,d)=>(e._remux_ts_to_mp4=Y.B)(a,b,c,d);e._malloc=a=>(e._malloc=Y.C)(a);var Ea=(a,b)=>(Ea=Y.E)(a,b),Da=a=>(Da=Y.F)(a),Ba=a=>(Ba=Y.G)(a),X=a=>(X=Y.H)(a),Aa=()=>(Aa=Y.I)();e._ff_h264_cabac_tables=148044;
e.cwrap=(a,b,c,d)=>{var f=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&f&&!d?e["_"+a]:(...g)=>Ca(a,b,c,g)};var Z;L=function Ga(){Z||Ha();Z||(L=Ga)};
function Ha(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!D)){Q(ja);h(e);e.onRuntimeInitialized?.();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();ka.unshift(b)}Q(ka)}}if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)la();Q(ia);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);a()},1)):a())}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();Ha();moduleRtn=aa;


  return moduleRtn;
}
);
})();
// CommonJS/AMD UMD tail removed: this is an ESM module (see worker/README.md
// "workerd portability notes"). Only the ESM export below is used.
export default FFmpegThumb;
